import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import './css/animate.css'
import './css/bootstrap.css'
// import './css/flaticon.css'
// import './css/fonticon.css'
import './css/magnify.css'
import './css/select.css'
import './css/slick.css'
import './css/slicknav.css'
import './css/styles.css'
import './css/styling.css'
// import './css/theme.css'
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';





import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        </body>
    </html>
  );
}
